### ISSUE TITLE
Genymotion emulators error

### ISSUE THREAD

**Issue by candy69** [VKCOM/devicehub#179]
While using genymotion emulators I'm getting this error when trying to use any of the emulated android devices:

![Image](https://github.com/user-attachments/assets/3302a932-a2d7-4988-96b9-27e2af730b86)

STFagent is installed automatically but I'm also getting the errors in the docker log after app startup like this:

devicehub-provider              | 2025-03-20T12:38:42.617Z INF/device:plugins:identity 44749 [192.168.242.112:5555] Solving identity
devicehub-provider              | 2025-03-20T12:38:42.619Z INF/device:resources:service 44805 [192.168.242.113:5555] Checking whether we need to install STFService
devicehub-provider              | 2025-03-20T12:38:42.619Z INF/device:resources:service 44805 [192.168.242.113:5555] Calling getPath()
devicehub-provider              | 2025-03-20T12:38:42.660Z INF/device:plugins:service 44760 [R6CY2001CAR] Launching service
devicehub-provider              | 2025-03-20T12:38:42.660Z INF/device:plugins:service 44760 [R6CY2001CAR] using 'start-foreground-service' command for API 34
devicehub-provider              | 2025-03-20T12:38:42.666Z INF/device:plugins:service 44760 [R6CY2001CAR] Agent says: "InputClient started"
devicehub-provider              | 2025-03-20T12:38:42.763Z INF/device:plugins:identity 44695 [R68T202S6BZ] Solving identity
devicehub-provider              | 2025-03-20T12:38:42.797Z INF/provider 1 [*] Starting to work
devicehub-provider              | 2025-03-20T12:38:42.797Z INF/provider 1 [*] Spawned a device worker
devicehub-provider              | 2025-03-20T12:38:42.891Z INF/device:resources:service 44805 [192.168.242.113:5555] getPath pm exec returned package:/data/app/~~DhjWrPcAITGL8dRU6OD02Q==/jp.co.cyberagent.stf-c20a7uw_qRswDblsbhB7mQ==/base.apk
devicehub-provider              | 2025-03-20T12:38:42.891Z INF/device:resources:service 44805 [192.168.242.113:5555] Running version check
devicehub-provider              | Attacted device udid: undefined; name: undefined
devicehub-provider              | 2025-03-20T12:38:42.896Z INF/device:plugins:solo 44749 [192.168.242.112:5555] Subscribing to permanent channel "woWayXi9jNvuMQLHM+zqSLWRMuc="
devicehub-provider              | 2025-03-20T12:38:42.897Z INF/device:plugins:screen:stream 44749 [192.168.242.112:5555] ScreenGrabber option set to minicap-bin
devicehub-provider              | 2025-03-20T12:38:42.897Z INF/device:plugins:screen:stream 44749 [192.168.242.112:5555] ScreenFrameRate option set to 20
devicehub-provider              | 2025-03-20T12:38:42.897Z INF/device:plugins:screen:stream 44749 [192.168.242.112:5555] Starting WebSocket server on port NaN
devicehub-provider              | 2025-03-20T12:38:42.901Z FTL/device 44749 [192.168.242.112:5555] Setup had an error RangeError [ERR_SOCKET_BAD_PORT]: options.port should be >= 0 and < 65536. Received type number (NaN).
devicehub-provider              |     at Server.listen (node:net:2055:5)
devicehub-provider              |     at new WebSocketServer (/app/node_modules/ws/lib/WebSocketServer.js:76:20)
devicehub-provider              |     at createServer (file:///app/lib/units/device/plugins/screen/stream.js:392:23)
devicehub-provider              |     at file:///app/lib/units/device/plugins/screen/stream.js:412:16
devicehub-provider              |     at ParallelSyrup.invoke (/app/node_modules/@devicefarmer/stf-syrup/lib/parallel.js:54:24)
devicehub-provider              |     at /app/node_modules/@devicefarmer/stf-syrup/lib/serial.js:43:33
devicehub-provider              |     at tryCatch1 (/app/node_modules/@devicefarmer/stf-syrup/node_modules/bluebird/js/main/util.js:63:19)
devicehub-provider              |     at Promise.Promise$_callHandler [as _callHandler] (/app/node_modules/@devicefarmer/stf-syrup/node_modules/bluebird/js/main/promise.js:708:13)
devicehub-provider              |     at Promise.Promise$_settlePromiseFromHandler [as _settlePromiseFromHandler] (/app/node_modules/@devicefarmer/stf-syrup/node_modules/bluebird/js/main/promise.js:724:18)
devicehub-provider              |     at Promise.Promise$_settlePromiseAt [as _settlePromiseAt] (/app/node_modules/@devicefarmer/stf-syrup/node_modules/bluebird/js/main/promise.js:896:14)
devicehub-provider              |     at Promise.Promise$_fulfillPromises [as _fulfillPromises] (/app/node_modules/@devicefarmer/stf-syrup/node_modules/bluebird/js/main/promise.js:1041:14)
devicehub-provider              |     at Async.Async$_consumeFunctionBuffer [as _consumeFunctionBuffer] (/app/node_modules/@devicefarmer/stf-syrup/node_modules/bluebird/js/main/async.js:74:12)
devicehub-provider              |     at Async$consumeFunctionBuffer (/app/node_modules/@devicefarmer/stf-syrup/node_modules/bluebird/js/main/async.js:37:14)
devicehub-provider              |     at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
devicehub-provider              | 2025-03-20T12:38:42.901Z FTL/util:lifecycle 44749 [192.168.242.112:5555] Shutting down due to fatal error with optional error :  undefined
devicehub-provider              | 2025-03-20T12:38:42.931Z INF/provider 1 [*] Cleaning up device worker "192.168.242.112:5555"
devicehub-provider              | 2025-03-20T12:38:42.931Z ERR/provider 1 [*] ExitError: Exit code "1"
devicehub-provider              |     at ChildProcess.exitListener (file:///app/lib/units/provider/index.js:158:41)
devicehub-provider              |     at ChildProcess.emit (node:events:519:28)
devicehub-provider              |     at ChildProcess.emit (node:domain:488:12)
devicehub-provider              |     at ChildProcess._handle.onexit (node:internal/child_process:294:12)
devicehub-provider              |     at Process.callbackTrampoline (node:internal/async_hooks:130:17) {
devicehub-provider              |   code: 1
devicehub-provider              | }
devicehub-provider              | 2025-03-20T12:38:42.932Z ERR/provider 1 [*] Device worker "192.168.242.112:5555" died with code 1

The workers on those devices seems to periodically restart, emulator screen goes dark for a few second, wakes up and cycle through. Is there any way to have ability to use emulators beside real phones. It's showing emulated phones in adb devices list and I also can connect to them via scrcpy app, but no luck with device hub.

Can I also contact you elsewhere beside vk? Can't seems to get it working. Can I please get your contacts please, maybe telegram, discord, email? Would like to discuss the possibility of partnership

**Comment by irdkwmnsb** [comment]
Hi!
Can you show how are you starting the provider?
Have you modified anything in the docker compose file? And which one are you using?

As per another way to contact us: At the moment it's either github discussions/issues or the VK chat. Sorry..
Although my personal contacts are in my github profile

**Comment by candy69** [comment]
> Hi! Can you show how are you starting the provider? Have you modified anything in the docker compose file? And which one are you using?
> 
> As per another way to contact us: At the moment it's either github discussions/issues or the VK chat. Sorry.. Although my personal contacts are in my github profile

Because my setup is about running adb host and farm host on different machines (it's okay on running physical phones), this is my docker-compose-prod.yaml:

```
networks:
    devicehub:
        driver: bridge

services:
    nginx:
        image: "nginx:bookworm"
        container_name: devicehub-nginx
        volumes:
            - ./scripts/nginx.conf:/etc/nginx/nginx.conf:ro
            - certs:/etc/nginx/ssl:ro
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            devicehub-app:
                condition: service_started
            devicehub-websocket:
                condition: service_started
            devicehub-storage-temp:
                condition: service_started
            devicehub-storage-plugin-apk:
                condition: service_started
            devicehub-storage-plugin-image:
                condition: service_started
            devicehub-api:
                condition: service_started
            devicehub-auth:
                condition: service_started
            devicehub-provider:
                condition: service_started
            devicehub-ssl:
                condition: service_completed_successfully
        restart: unless-stopped
        networks:
            devicehub:
    adbd:
        container_name: adbd
        image: "devicefarmer/adb:latest"
        restart: unless-stopped
        volumes:
            - /dev/bus/usb:/dev/bus/usb
        privileged: true
        healthcheck:
**Modified** >>>     test: nc -vz 10.99.0.63 5037
            interval: 1m30s
            timeout: 30s
            retries: 5
            start_period: 30s
        networks:
            devicehub:
    devicehub-mongo:
        image: mongo:7.0
        hostname: devicehub-mongo
        container_name: devicehub-mongo
        ports:
            - 27017:27017
        entrypoint: ["mongod", "--replSet", "devicehub-rs", "--bind_ip_all"]
        healthcheck:
            test: echo "rs.status()" | mongosh --port 27017 --quiet
            interval: 5s
            timeout: 30s
            start_period: 0s
            start_interval: 1s
            retries: 30
        networks:
            devicehub:
        volumes:
            - devicehub-db-volume:/opt/devicehub/db
    devicehub-mongosetup:
        image: mongo:7.0
        container_name: devicehub-mongosetup
        depends_on:
            devicehub-mongo:
                condition: service_healthy
        volumes:
            - ./scripts/mongo_setup.sh:/scripts/mongo_setup.sh
        restart: "no"
        entrypoint: ["bash", "/scripts/mongo_setup.sh"]
        networks:
            devicehub:
    devicehub-migrate:
        build: .
        image: vkcom/devicehub
        container_name: devicehub-migrate
        env_file:
            - scripts/variables.env
        command: stf migrate
        depends_on:
            devicehub-mongosetup:
                condition: service_completed_successfully
        networks:
            devicehub:
    devicehub-app:
        build: .
        image: vkcom/devicehub
        container_name: devicehub-app
        env_file:
            - scripts/variables.env
        command: stf app --port 3000 --auth-url https://${STF_DOMAIN}:${STF_PORT}/${AUTH_URL} --websocket-url https://${STF_DOMAIN}:${STF_PORT}/ --secret=${STF_SECRET}
        depends_on:
            devicehub-migrate:
                condition: service_completed_successfully
        restart: unless-stopped
        networks:
            devicehub:
    devicehub-auth:
        build: .
        image: vkcom/devicehub
        container_name: devicehub-auth
        env_file:
            - scripts/variables.env
        command: stf auth-mock --port 3000 --app-url https://${STF_DOMAIN}:${STF_PORT} --secret=${STF_SECRET}
        depends_on:
            devicehub-migrate:
                condition: service_completed_successfully
        restart: unless-stopped
        networks:
            devicehub:
    devicehub-processor001:
        build: .
        image: vkcom/devicehub
        container_name: devicehub-processor001
        env_file:
            - scripts/variables.env
        command: stf processor --name proc001 --connect-app-dealer tcp://devicehub-triproxy-app:7160 --connect-dev-dealer tcp://devicehub-triproxy-dev:7260
        depends_on:
            devicehub-migrate:
                condition: service_completed_successfully
        restart: unless-stopped
        networks:
            devicehub:
    devicehub-reaper:
        build: .
        image: vkcom/devicehub
        container_name: devicehub-reaper
        env_file:
            - scripts/variables.env
        command: stf reaper --name reaper001 --connect-push tcp://devicehub-triproxy-dev:7270 --connect-sub tcp://devicehub-triproxy-app:7150 --heartbeat-timeout 30000
        depends_on:
            devicehub-migrate:
                condition: service_completed_successfully
        restart: unless-stopped
        networks:
            devicehub:
    devicehub-storage-plugin-apk:
        build: .
        image: vkcom/devicehub
        container_name: devicehub-storage-plugin-apk
        env_file:
            - scripts/variables.env
        command: stf storage-plugin-apk --port 3000 --storage-url http://devicehub-storage-temp/ --secret=${STF_SECRET}
        depends_on:
            devicehub-migrate:
                condition: service_completed_successfully
        restart: unless-stopped
        networks:
            devicehub:
    devicehub-storage-plugin-image:
        build: .
        image: vkcom/devicehub
        container_name: devicehub-storage-plugin-image
        env_file:
            - scripts/variables.env
        command: stf storage-plugin-image --port 3000 --storage-url https://${STF_DOMAIN}:${STF_PORT}/ --secret=${STF_SECRET}
        depends_on:
            devicehub-migrate:
                condition: service_completed_successfully
        restart: unless-stopped
        networks:
            devicehub:
    devicehub-storage-temp:
        build: .
        image: vkcom/devicehub
        container_name: devicehub-storage-temp
        env_file:
            - scripts/variables.env
        command: stf storage-temp --port 3000 --save-dir /tmp --connect-sub tcp://devicehub-triproxy-app:7150 --connect-push tcp://devicehub-triproxy-app:7170 --secret=${STF_SECRET}
        depends_on:
            devicehub-migrate:
                condition: service_completed_successfully
        restart: unless-stopped
        networks:
            devicehub:
    devicehub-triproxy-app:
        build: .
        image: vkcom/devicehub
        container_name: devicehub-triproxy-app
        env_file:
            - scripts/variables.env
        command: stf triproxy app001 --bind-pub "tcp://*:7150" --bind-dealer "tcp://*:7160" --bind-pull "tcp://*:7170"
        ports:
            - "7150:7150"
            - "7160:7160"
            - "7170:7170"
        depends_on:
            devicehub-migrate:
                condition: service_completed_successfully
        restart: unless-stopped
        networks:
            devicehub:
    devicehub-triproxy-dev:
        build: .
        image: vkcom/devicehub
        container_name: devicehub-triproxy-dev
        env_file:
            - scripts/variables.env
        command: stf triproxy --name dev001 --bind-pub "tcp://*:7250" --bind-dealer "tcp://*:7260" --bind-pull "tcp://*:7270"
        ports:
            - "7250:7250"
            - "7260:7260"
            - "7270:7270"
        depends_on:
            devicehub-migrate:
                condition: service_completed_successfully
        restart: unless-stopped
        networks:
            devicehub:
    devicehub-websocket:
        build: .
        image: vkcom/devicehub
        container_name: devicehub-websocket
        env_file:
            - scripts/variables.env
        command: stf websocket --port 3000 --storage-url https://${STF_DOMAIN}:${STF_PORT}/ --connect-sub tcp://devicehub-triproxy-app:7150 --connect-push tcp://devicehub-triproxy-app:7170 --secret=${STF_SECRET}
        depends_on:
            devicehub-migrate:
                condition: service_completed_successfully
        restart: unless-stopped
        networks:
            devicehub:
    devicehub-api:
        build: .
        image: vkcom/devicehub
        container_name: devicehub-api
        env_file:
            - scripts/variables.env
        command: stf api --port 3000 --connect-sub tcp://devicehub-triproxy-app:7150 --connect-push tcp://devicehub-triproxy-app:7170 --connect-sub-dev tcp://devicehub-triproxy-dev:7250 --connect-push-dev tcp://devicehub-triproxy-dev:7270 --secret=${STF_SECRET}
        depends_on:
            devicehub-migrate:
                condition: service_completed_successfully
        restart: unless-stopped
        networks:
            devicehub:
    devicehub-api-groups-engine:
        build: .
        image: vkcom/devicehub
        container_name: devicehub-api-groups-engine
        env_file:
            - scripts/variables.env
        command: stf groups-engine --connect-sub tcp://devicehub-triproxy-app:7150 --connect-push tcp://devicehub-triproxy-app:7170 --connect-sub-dev tcp://devicehub-triproxy-dev:7250 --connect-push-dev tcp://devicehub-triproxy-dev:7270
        depends_on:
            devicehub-migrate:
                condition: service_completed_successfully
        restart: unless-stopped
        networks:
            devicehub:
    devicehub-provider:
        build: .
        image: vkcom/devicehub
        container_name: devicehub-provider
        env_file:
            - scripts/variables.env
        depends_on:
            devicehub-migrate:
                condition: service_completed_successfully
            adbd:
                condition: service_healthy
        restart: unless-stopped
  **Modified** >>>     command: stf provider --name devicehub-provider --allow-remote --adb-host 10.99.0.63 --adb-port 5037 --no-cleanup --connect-sub tcp://devicehub-triproxy-dev:7250 --connect-push tcp://devicehub-triproxy-dev:7270 --storage-url https://${STF_DOMAIN}:${STF_PORT}/ --public-ip https://${STF_DOMAIN}:${STF_PORT} --min-port=12010 --max-port=12100 --heartbeat-interval 10000 --screen-ws-url-pattern "wss://${STF_DOMAIN}:${STF_PORT}/d/devicehub-provider/<%= publicPort %>/"
        networks:
            devicehub:
    devicehub-ssl:
        image: paulczar/omgwtfssl
        environment:
            - SSL_SUBJECT=${STF_DOMAIN}:${STF_PORT}
        volumes:
            - certs:/certs:rw
volumes:
    devicehub-db-volume:
    certs:
```
