### ISSUE TITLE
Ошибка "TypeError: passport.use is not a function" при запуске auth-oauth2

### ISSUE THREAD

**Issue by mommys-little-hacker** [VKCOM/devicehub#246]
Часть манифеста docker-compose:
```
devicehub-auth:
    image: ghcr.io/vkcom/devicehub:v1.4.3
    container_name: devicehub-auth
    environment:
      TZ: Europe/Moscow
      MONGODB_PORT_27017_TCP: mongodb://devicehub-mongo:27017
      STF_AUTH_OAUTH2_SECRET: ****
      STF_AUTH_OAUTH2_APP_URL: https://****
      STF_AUTH_OAUTH2_PORT: "7120"
      STF_AUTH_OAUTH2_OAUTH_AUTHORIZATION_URL: https://****/oauth/authorize
      STF_AUTH_OAUTH2_OAUTH_TOKEN_URL: https://****/oauth/token
      STF_AUTH_OAUTH2_OAUTH_USERINFO_URL: https://****/oauth/userinfo
      STF_AUTH_OAUTH2_OAUTH_CLIENT_ID: ****
      STF_AUTH_OAUTH2_OAUTH_CLIENT_SECRET: ****
      STF_AUTH_OAUTH2_OAUTH_CALLBACK_URL: https://****/auth/oauth/callback
      STF_AUTH_OAUTH2_OAUTH_SCOPE: openid email
    command: stf auth-oauth2
    depends_on:
      devicehub-migrate:
        condition: service_completed_successfully
    restart: unless-stopped
    networks:
      - devicehub
    ports:
      - 7120:7120
```

Контейнер падает со следующим выводом:
```
Initialized sentry for environment: unset
Warning: Sentry sample_rate is 0
(node:1) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
172.18.0.12
Starting DeviceHub
stf auth-oauth2

Start an OAuth 2.0 auth unit.

Options:
  -h, --help                     Show help.                            [boolean]
  -a, --app-url                  URL to the app unit.        [string] [required]
      --oauth-authorization-url  OAuth 2.0 authorization URL.[string] [required]
      --oauth-token-url          OAuth 2.0 token URL.        [string] [required]
      --oauth-userinfo-url       OAuth 2.0 user info URL.    [string] [required]
      --oauth-client-id          OAuth 2.0 client ID.        [string] [required]
      --oauth-client-secret      OAuth 2.0 client secret.    [string] [required]
      --oauth-callback-url       OAuth 2.0 callback URL.     [string] [required]
      --oauth-scope              Space-separated OAuth 2.0 scope.
                                                             [string] [required]
      --oauth-state              Whether to enable OAuth 2.0 state token support
                                 .                    [boolean] [default: false]
      --oauth-domain             Optional email domain to allow authentication f
                                 or.                                    [string]
  -p, --port                     The port to bind to.   [number] [default: 7120]
  -s, --secret                   The secret to use for auth JSON Web Tokens. Any
                                 one who knows this token can freely enter the s
                                 ystem if they want, so keep it safe.
                                                             [string] [required]
  -i, --ssid                     The name of the session ID cookie.
                                                      [string] [default: "ssid"]
      --support, --sl            url which needed to access support
                                               [string] [default: "example.com"]
      --docsUrl, --du            url which needed to access docs
                                               [string] [default: "example.com"]
  -V, --version                  Show version number                   [boolean]

Each option can be be overwritten with an environment variable by converting the
 option to uppercase, replacing dashes with underscores and prefixing it with `S
TF_AUTH_OAUTH2_` (e.g. `STF_AUTH_OAUTH2_SECRET`). Legacy environment variables l
ike OAUTH_SCOPE are still accepted, too, but consider them deprecated.

TypeError: passport.use is not a function
    at default (file:///app/lib/units/auth/oauth2/index.js:42:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```
